controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

    # DexController parameters
    FollowPath:
      plugin: "dex_controller::DexController"
      ang_max_vel: 1.5705
      lin_max_vel: 1.0
      lookahead: 0.3
      ang_tol: 0.1
      lin_tol: 0.1
      kp_ang: 5.0
      kp_lin: 5.0
      granularity: 100
      stuck_thr: 0.01