controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

    # DexController parameters
    FollowPath:
      plugin: "dex_controller::DexController"
      ang_max_vel: 1.5705
      lin_max_vel: 0.3
      lookahead: 0.25
      ang_tol: 0.4
      lin_tol: 0.23
      kp_ang: 4.0
      kp_lin: 10.0